### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by azamet90** [cy4nguy/Python-Ransomware#1]
i just tryed that file without editing/changing anything... just to exe with pyinstaller it says something is failed and the command prompt dissappear very fast and nothing encrypted... my avast antivirus did not detect it which is good but not working

**Comment by cy4nguy** [comment]
Can you send me the Error ?!

**Comment by azamet90** [comment]
> Can you send me the Error ?!

i did removed it after that but there was no error message it was opening and closing very fast

**Comment by cy4nguy** [comment]
Run it Throw cmd to see the error log.
And in pyinstaller don't use -w

**Comment by cy4nguy** [comment]
not enough info.
